### ISSUE TITLE
Link to singlefile gistpreview

### ISSUE THREAD

**Issue by Monster0506** [Coding-with-love/cross#1]
Hi! 

I took the liberty of putting this in a single index.html file, and then creating a gist. Feel free to use this?
Preview Link:
[preview link](https://gistpreview.github.io/?3b6655ecc0978360e49eaf41dbf2e52a)
Gist Link:
[gist link](https://gist.github.com/Monster0506/3b6655ecc0978360e49eaf41dbf2e52a)

Have a great day!

**Comment by Coding-with-love** [comment]
Thank you! Added the link.

**Comment by loveconnor** [comment]
Thank you! Added the link.
